//
// Machine.hpp for  in /home/nicolaschr/rendu/hellRush/purgatory/etape1
//
// Made by Nicolas Charvoz
// Login   <nicolaschr@epitech.net>
//
// Started on  Tue Nov 24 17:55:55 2015 Nicolas Charvoz
// Last update Fri Nov 27 12:51:52 2015 Antoine Garcia
//

#include "Machine.hpp"

eState gStateTable[8][8] = {
  {S1, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  {STATE_ERROR, S2, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  {STATE_ERROR, S2, S3, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  {STATE_ERROR, STATE_ERROR, STATE_ERROR, S4, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S5, STATE_ERROR, STATE_ERROR, STATE_ERROR},
  {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S6, STATE_ERROR, STATE_ERROR},
  {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S7, STATE_ERROR},
  {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
};

eAction  gActionTable[8][8] = {
  {MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  {ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  {ACTION_ERROR, MA, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
  {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR},
  {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR},
  {HR,           HR,           HR,           HR,           HR,           HR,           HR, HR},
};
